name: APPLE
options:
  xcodeVersion: '15.0'
  minimumXcodeGenVersion: '2.25.0'
  deploymentTarget:
    iOS: "16.0"
  groupSortPosition: top
  developmentLanguage: ru

settings:
  base:
    APP_VERSION: 1.0.0
    BUNDLE_VERSION: 1
    ENABLE_BITCODE: no
    DISPLAY_NAME: APPLE

appFonts: &app_Fonts [
  CustomFont.ttf
]

packages:
  SnapKit:
    url: https://github.com/SnapKit/SnapKit.git
    from: 5.0.1
  AppMetricaCore:
    url: https://github.com/appmetrica/appmetrica-sdk-ios.git
    version: 5.5.0
  Doca:
    url: https://github.com/pcfcocean/doca.git
    from: 1.0.0
  MagicLayout:
    url: https://github.com/pcfcocean/magic-layout.git
    from: 1.0.0

targets:
  MainTarget:
    type: application
    platform: iOS
    deploymentTarget: 16.0
    sources:
      - path: ./MainTarget
    info:
      path: ./MainTarget/info.plist
      properties:
        CFBundleDisplayName: ${DISPLAY_NAME}
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.pcfcocean
    dependencies:
      - package: SnapKit
      - package: AppMetricaCore
      - package: Doca
      - package: MagicLayout
